/**
 * Applies pending SQL migrations (generated by `npm run db:generate`,
 * committed under backend/drizzle/) to whatever database DATABASE_URL
 * points at. Run this before starting the server — the Docker image's
 * CMD does this automatically on every container start.
 */
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { db, pool } from "./client.js";

async function main() {
  await migrate(db, { migrationsFolder: new URL("../../drizzle", import.meta.url).pathname });
  console.log("Migrations applied.");
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
